import os
import shutil
import subprocess
import sys
import tempfile

import numpy as np
import scipy.io.wavfile
import torch

# Premium Male Assistant Voices downloaded directly from hexgrad/Kokoro-82M
MALE_ASSISTANT_VOICE = ["bm_lewis"]
CURRENT_VOICE_INDEX = 0


def find_audio_player():
    for player in ("aplay", "paplay", "ffplay", "afplay"):
        if shutil.which(player):
            return player
    return None


def play_wav(path):
    player = find_audio_player()
    if not player:
        print("No audio player found. WAV saved at", path)
        return
    if player == "ffplay":
        cmd = ["ffplay", "-nodisp", "-autoexit", path]
    else:
        cmd = [player, path]
    p = subprocess.Popen(
        cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
    )
    p.wait()


_PIPELINE_CACHE = None


def _load_kokoro_pipeline():
    """Initialises and caches the native PyTorch Kokoro pipeline.
    
    This loads the weights directly from hexgrad/Kokoro-82M on Hugging Face.
    """
    global _PIPELINE_CACHE
    if _PIPELINE_CACHE is not None:
        return _PIPELINE_CACHE

    from kokoro import KPipeline

    print("Loading Kokoro-82M via PyTorch (pulling weights from Hugging Face)...")
    # 'a' defaults to American English, but it handles British ('p') variants automatically.
    pipeline = KPipeline(lang_code="a")
    _PIPELINE_CACHE = pipeline
    return pipeline


def synthesize_local(text, voice_name, out_path):
    pipeline = _load_kokoro_pipeline()

    # Dynamically match language codes ('a' for American English, 'b' for British English)
    lang = "b" if voice_name.startswith("pm_") else "a"
    pipeline.lang_code = lang

    # Generate using PyTorch. The pipeline yields generator chunks.
    generator = pipeline(text, voice=voice_name, speed=1.0, split_pattern=r"\n")
    
    all_audio = []
    for _, _, audio in generator:
        if audio is not None:
            all_audio.append(audio)

    if not all_audio:
        raise ValueError("No audio was generated by the PyTorch model.")

    # Stack the audio chunks together
    waveform = torch.cat(all_audio).cpu().numpy()
    sample_rate = 24000  # Kokoro standard high-fidelity output

    # Normalise audio matrix to standard playable 16-bit PCM WAV format
    waveform = np.clip(waveform, -1.0, 1.0)
    pcm = (waveform * 32767).astype(np.int16)
    scipy.io.wavfile.write(out_path, sample_rate, pcm)


def main():
    global CURRENT_VOICE_INDEX

    print("🤖 Kokoro Native PyTorch Assistant Voice Tester (Hugging Face Hub)")
    print("----------------------------------------------------------------")
    print(f"Premium male voices to loop: {MALE_ASSISTANT_VOICE}")
    print("Type text and press Enter to speak. Type 'quit' or Ctrl-D to exit.\n")

    try:
        while True:
            try:
                text = input("TTS> ").strip()
            except EOFError:
                print()
                break
            if not text:
                continue
            if text.lower() in ("quit", "exit"):
                break

            # Handle explicit forced voice triggers matching the format of your original script
            if text.startswith("@"):
                parts = text.split(" ", 1)
                if len(parts) == 2:
                    voice = parts[0][1:]
                    text = parts[1]
                    print(f"-> Forcing Voice: {voice}")
                else:
                    voice = MALE_ASSISTANT_VOICE[CURRENT_VOICE_INDEX]
            else:
                # Sequential Voice Rotation Loop Mode
                voice = MALE_ASSISTANT_VOICE[CURRENT_VOICE_INDEX]
                print(f"[Loop Mode] Auditioning Male Voice: {voice}")
                CURRENT_VOICE_INDEX = (CURRENT_VOICE_INDEX + 1) % len(
                    MALE_ASSISTANT_VOICE
                )

            with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as f:
                out = f.name
            try:
                synthesize_local(text, voice, out)
                play_wav(out)
            except Exception as e:
                print("TTS error:", e, file=sys.stderr)
            finally:
                try:
                    os.unlink(out)
                except Exception:
                    pass
    finally:
        print("Exiting interactive TTS.")


if __name__ == "__main__":
    main()