#!/usr/bin/env python3
import os
import queue
import shutil
import subprocess
import tempfile
import threading
import rospy
import numpy as np
import scipy.io.wavfile
from std_msgs.msg import String


def _env_int(name, default):
    try:
        return int(os.getenv(name, str(default)))
    except ValueError:
        return default


def _env_float(name, default):
    try:
        return float(os.getenv(name, str(default)))
    except ValueError:
        return default


class _LocalKokoroTTS:
    """Kokoro-82M TTS wrapper exposing a tts_to_file() interface.

    Uses hexgrad/Kokoro-82M via the ``kokoro`` package (KPipeline).
    Follows the same lazy-init / fallback pattern as WhisperTinyTranscriber's
    ``_ensure_pipeline_loaded()``.
    """

    def __init__(self, voice="bm_lewis", lang_code="a", speed=1.0):
        self.voice = voice
        self.lang_code = lang_code
        self.speed = speed
        self._pipeline = None
        self._load_error = None

    def _ensure_pipeline_loaded(self):
        """Lazy-load & cache the Kokoro KPipeline (mirrors WhisperTiny pattern)."""
        if self._pipeline is not None:
            return True
        if self._load_error is not None:
            return False
        try:
            from kokoro import KPipeline  # noqa: F811
            self._pipeline = KPipeline(lang_code=self.lang_code)
            return True
        except Exception as exc:
            self._load_error = str(exc)
            return False

    def tts_to_file(self, text, file_path, speaker=None):
        import torch

        if not self._ensure_pipeline_loaded():
            raise RuntimeError(
                "Kokoro pipeline not available: %s"
                % (self._load_error or "unknown error")
            )

        voice = str(speaker) if speaker else self.voice
        
        # FIXED: Congruent dynamic language selector alignment matching template code base
        lang = "b" if voice.startswith(("bm_", "pm_", "bf_", "pf_")) else "a"
        self._pipeline.lang_code = lang

        generator = self._pipeline(
            text, voice=voice, speed=self.speed, split_pattern=r"\n"
        )

        all_audio = []
        for _, _, audio in generator:
            if audio is not None:
                all_audio.append(audio)

        if not all_audio:
            raise ValueError("No audio was generated by the Kokoro pipeline.")

        waveform = torch.cat(all_audio).cpu().numpy()
        waveform = np.clip(waveform, -1.0, 1.0)
        pcm = (waveform * 32767).astype(np.int16)
        scipy.io.wavfile.write(file_path, 24000, pcm)  # Kokoro standard sample rate


class JunoTTSNode:
    """ROS TTS node for JUNO responses."""

    def __init__(self):
        rospy.init_node('juno_tts_node', anonymous=True)
        self.tts_topic = rospy.get_param('~tts_topic', os.getenv('JUNO_TTS_TOPIC', '/juno/tts'))
        self.stop_topic = rospy.get_param('~tts_stop_topic', os.getenv('JUNO_TTS_STOP_TOPIC', '/juno/tts_stop'))
        self.done_topic = rospy.get_param('~tts_done_topic', os.getenv('JUNO_TTS_DONE_TOPIC', '/juno/tts_done'))
        self.voice_locale = rospy.get_param('~voice_locale', os.getenv('JUNO_TTS_VOICE_LOCALE', 'en_GB'))
        self.rate = int(rospy.get_param('~rate', _env_int('JUNO_TTS_RATE', 165)))
        self.done_delay = float(rospy.get_param('~done_delay', _env_float('JUNO_TTS_DONE_DELAY', 1.0)))
        self.backend = str(rospy.get_param('~backend', os.getenv('JUNO_TTS_BACKEND', 'kokoro'))).strip().lower()
        self.command_setting = str(rospy.get_param('~command', os.getenv('JUNO_TTS_COMMAND', 'auto'))).strip()
        self.audio_player = rospy.get_param('~audio_player', os.getenv('JUNO_TTS_AUDIO_PLAYER', 'auto')).strip()

        self.kokoro_enabled = bool(str(rospy.get_param('~kokoro_enabled', os.getenv('JUNO_TTS_KOKORO_ENABLED', 'true'))).lower() in ('1', 'true', 'yes'))
        self.kokoro_voice = rospy.get_param('~kokoro_voice', os.getenv('JUNO_TTS_KOKORO_VOICE', 'bm_lewis'))
        self.kokoro_lang_code = rospy.get_param('~kokoro_lang_code', os.getenv('JUNO_TTS_KOKORO_LANG_CODE', 'a'))
        self.kokoro_speed = float(rospy.get_param('~kokoro_speed', os.getenv('JUNO_TTS_KOKORO_SPEED', '1.0')))

        self.coqui = None  
        self.queue = queue.Queue()
        self.done_pub = rospy.Publisher(self.done_topic, String, queue_size=1, latch=True)
        self._stop_event = threading.Event()
        self._current_process = None
        self._process_lock = threading.Lock()

        if self.backend not in {'kokoro', 'espeak'}:
            rospy.logwarn('Invalid JUNO_TTS_BACKEND=%s. Falling back to kokoro.', self.backend)
            self.backend = 'kokoro'

        if self.backend == 'kokoro':
            self._init_coqui()

        rospy.Subscriber(self.tts_topic, String, self.callback, queue_size=10)
        rospy.Subscriber(self.stop_topic, String, self.stop_callback, queue_size=10)

        self.worker = threading.Thread(target=self._worker_loop, daemon=True)
        self.worker.start()

    def _init_coqui(self):
        if not self.kokoro_enabled:
            return
        try:
            kokoro_tts = _LocalKokoroTTS(
                voice=self.kokoro_voice,
                lang_code=self.kokoro_lang_code,
                speed=self.kokoro_speed,
            )
            if kokoro_tts._ensure_pipeline_loaded():
                self.coqui = kokoro_tts
                rospy.loginfo('Initialized Kokoro-82M TTS (voice=%s)', self.kokoro_voice)
            else:
                rospy.logwarn('Kokoro pipeline failed to load: %s. Falling back to espeak.', kokoro_tts._load_error)
        except Exception as exc:
            rospy.logwarn('Kokoro-82M unavailable: %s. Falling back to espeak.', exc)

    def callback(self, msg):
        text = str(msg.data).strip()
        if not text:
            return
        self.queue.put(text)

    def stop_callback(self, _msg):
        self._stop_event.set()
        self._clear_speech_queue()
        with self._process_lock:
            process = self._current_process
        if process is not None and process.poll() is None:
            try:
                process.terminate()
            except Exception as exc:
                rospy.logwarn('Could not terminate process cleanly: %s', exc)
        self.done_pub.publish(String(data='stopped'))

    def _clear_speech_queue(self):
        while True:
            try:
                self.queue.get_nowait()
                self.queue.task_done()
            except queue.Empty:
                break

    def _worker_loop(self):
        while not rospy.is_shutdown():
            try:
                text = self.queue.get(timeout=0.2)
            except queue.Empty:
                continue
            try:
                self._speak(text)
            except Exception as exc:
                rospy.logerr('JUNO TTS failed for text %r: %s', text, exc)
            finally:
                rospy.sleep(0.05 if self._stop_event.is_set() else self.done_delay)
                self.done_pub.publish(String(data='done'))
                self._stop_event.clear()
                self.queue.task_done()

    def _speak(self, text):
        if self._stop_event.is_set():
            return
        if self.backend == 'kokoro' and self.coqui is not None:
            self._speak_with_coqui(text)
            return
        self._speak_with_espeak(text)

    def _candidate_commands(self):
        if self.command_setting and self.command_setting.lower() != 'auto':
            return [self.command_setting]
        return ['espeak-ng', 'espeak']

    def _candidate_audio_players(self):
        if self.audio_player and self.audio_player.lower() != 'auto':
            return [self.audio_player]
        return ['aplay', 'paplay', 'ffplay', 'afplay']

    def _candidate_voices(self):
        requested = self.voice_locale.strip().lower().replace('_', '-')
        voices = [requested] if requested else []
        voices.extend(['en-gb', 'en-uk', 'en-rp', 'en'])
        return list(dict.fromkeys(voices))

    def _speak_with_espeak(self, text):
        last_error = None
        for command in self._candidate_commands():
            if shutil.which(command) is None:
                continue
            for voice in self._candidate_voices():
                args = [command, '-v', voice, '-s', str(self.rate), text]
                process = subprocess.Popen(args)
                with self._process_lock:
                    self._current_process = process
                while process.poll() is None:
                    if self._stop_event.is_set() or rospy.is_shutdown():
                        process.terminate()
                        return
                    rospy.sleep(0.05)
                if process.returncode == 0:
                    return
        raise RuntimeError('No espeak-compatible command available')

    def _speak_with_coqui(self, text):
        audio_file = None
        try:
            with tempfile.NamedTemporaryFile(suffix='.wav', delete=False) as tmp:
                audio_file = tmp.name
            self.coqui.tts_to_file(text=text, file_path=audio_file, speaker=self.kokoro_voice)
            
            for player in self._candidate_audio_players():
                if shutil.which(player) is None:
                    continue
                
                # FIXED: Added headless flags for ffplay execution layout consistency
                if player == "ffplay":
                    args = ["ffplay", "-nodisp", "-autoexit", audio_file]
                else:
                    args = [player, audio_file]

                process = subprocess.Popen(args, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
                with self._process_lock:
                    self._current_process = process
                while process.poll() is None:
                    if self._stop_event.is_set() or rospy.is_shutdown():
                        process.terminate()
                        return
                    rospy.sleep(0.05)
                if process.returncode == 0:
                    return
        finally:
            if audio_file and os.path.exists(audio_file):
                os.remove(audio_file)

    def run(self):
        rospy.spin()


if __name__ == '__main__':
    node = JunoTTSNode()
    node.run()